algo= input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(algo)))
print('Só tem espaço? {}'.format(algo.isspace()))
print('É um numero? {}'.format(algo.isnumeric()))
print('É alfabético? {}'.format(algo.isalpha()))
print('É alfanumérico {}'.format(algo.isalnum()))
print('Está em letra maiúsculas? {}'.format(algo.isupper()))
print('Esta em letras minúsculas? {}'.format(algo.islower()))
print('Esta capitalizada? {}'.format(algo.istitle()))
