algo= input('Digite algo: ')
print('O tipo primitivo desse valor é {}{}{}'.format('\033[1;34;40m', type(algo), '\033[m'))
print('Só tem espaço? {}{}{}'.format('\033[1;33;45m', algo.isspace(), '\033[m'))
print('É um numero? {}'.format(algo.isnumeric()))
print('É alfabético? {}'.format(algo.isalpha()))
print('É alfanumérico {}'.format(algo.isalnum()))
print('Está em letra maiúsculas? {}'.format(algo.isupper()))
print('Esta em letras minúsculas? {}'.format(algo.islower()))
print('Esta capitalizada? {}'.format(algo.istitle()))
